### ISSUE TITLE
[Feature Request] - Rewrite in ctypes

### ISSUE THREAD

**Issue by emmatyping** [schurpf/pyhk#1]
I know this would be difficult (probably not for you though), but my request is that you rewrite this awesome library in ctypes. Not all implementations of python work with win32api etc. This would make it amazing. Thanks!

**Comment by schurpf** [comment]
@IronManMark20 Thanks for the kind words :) Sorry but won't be able to rewrite this. Maybe somebody over at pyhook can do it? Gl.

**Comment by emmatyping** [comment]
I implemented my own hooks etc. The code is [here](https://github.com/IronManMark20/hooked). There you go. It wasn't as hard as I expected it to be.

**Comment by schurpf** [comment]
outstanding! added you on pyhk as alternative.

Speak soon!

On Tue, Apr 21, 2015 at 5:05 AM, IronManMark20 notifications@github.com
wrote:

> I implemented my own hooks etc. The code is here
> https://github.com/IronManMark20/hooked. There you go, Wasn't as hard
> as I expected.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/schurpf/pyhk/issues/1#issuecomment-94623934.

## 

_Michael Schurpf_
WordPress Engineer
p:+521 55 1916 6666 | e:michael@schurpf.com | w:http://schurpf.com
https://www.facebook.com/schurpf  https://www.linkedin.com/in/schurpf
https://twitter.com/schurpf
https://plus.google.com/u/0/+MichaelSchurpf1
https://www.youtube.com/user/schurpf

There are no problems only solutions!

Get the Top 8 WordPress Developer Tools: http://schurpf.com/email/top-8-
tools

**Comment by emmatyping** [comment]
Thanks. I should add pyhk to my Readme.
